[package]
name = "tennis"
version = "0.1.0"
authors = ["Nick Gravelyn <nick@nickgravelyn.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0.0-beta.2"
futures = { version = "0.3.13", features = ["thread-pool"] }
notify = "4.0.15"
tokio = { version = "1.4.0", features = ["full"] }
warp = "0.3.0"
